
import { useState } from 'react';
import Header from '@/components/Header';
import LogCard from '@/components/LogCard';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { mockLogs } from '@/data/mockLogs.tsx';
import { LogEntry } from '@/types';
import { PlusCircle, Baby } from 'lucide-react';

const Index = () => {
  const [logs, setLogs] = useState<LogEntry[]>(mockLogs || []);
  const [newLogTitle, setNewLogTitle] = useState('');
  const [newLogDescription, setNewLogDescription] = useState('');

  const handleAddLog = (e: React.FormEvent) => {
    e.preventDefault();
    if (!newLogTitle || !newLogDescription) return;

    const newLog: LogEntry = {
      id: Date.now(),
      timestamp: new Date().toISOString(),
      author: 'Parent',
      authorIcon: <Baby className="h-5 w-5 text-gray-500" />,
      original_entry: {
        title: newLogTitle,
        description: newLogDescription,
      },
      // In a real app, these would be generated by AI
      summary_for_teacher: `[AI Summary for Teacher]: Based on the parent's note about "${newLogTitle}", please observe the child for related behaviors in the classroom environment.`,
      summary_for_doctor: `[AI Summary for Doctor]: Patient's parent reports: "${newLogTitle}". Description: "${newLogDescription}". Correlate with patient history.`,
      tags: ['new', 'manual entry'],
    };

    setLogs([newLog, ...logs]);
    setNewLogTitle('');
    setNewLogDescription('');
  };

  return (
    <div className="min-h-screen bg-background">
      <Header />
      <main className="container mx-auto px-4 md:px-8 pb-12">
        <div className="grid gap-12 md:grid-cols-3">
          <div className="md:col-span-2 space-y-6">
            <h2 className="text-xl font-semibold text-foreground">Child's Timeline</h2>
            {logs.map(log => (
              <LogCard key={log.id} log={log} />
            ))}
          </div>
          <div className="space-y-6">
            <h2 className="text-xl font-semibold text-foreground">Log a New Event</h2>
            <Card>
              <CardHeader>
                <CardTitle>What's happening?</CardTitle>
                <CardDescription>
                  Log anything—a behavior, a feeling, a question for the doctor.
                </CardDescription>
              </CardHeader>
              <CardContent>
                <form onSubmit={handleAddLog} className="space-y-4">
                  <Input
                    placeholder="Title (e.g., 'Tummy ache after lunch')"
                    value={newLogTitle}
                    onChange={(e) => setNewLogTitle(e.target.value)}
                  />
                  <Textarea
                    placeholder="Describe what happened..."
                    value={newLogDescription}
                    onChange={(e) => setNewLogDescription(e.target.value)}
                    rows={5}
                  />
                  <Button type="submit" className="w-full">
                    <PlusCircle className="mr-2 h-4 w-4" />
                    Add to Timeline
                  </Button>
                </form>
              </CardContent>
            </Card>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Index;
