
import { LogEntry } from '@/types';
import { Baby } from 'lucide-react';

// This is a mock API function that simulates submitting a new log to a server.
// It will be replaced with a real API call once the backend is connected.
export const submitLog = async (
  logData: { title: string; description: string }
): Promise<LogEntry> => {
  console.log("Submitting log to mock API:", logData);

  const { title, description } = logData;

  // Simulate network delay
  await new Promise(resolve => setTimeout(resolve, 500));

  const newLog: LogEntry = {
    id: Date.now(),
    timestamp: new Date().toISOString(),
    author: 'Parent',
    authorIcon: <Baby className="h-5 w-5 text-gray-500" />,
    original_entry: {
      title: title,
      description: description,
    },
    // In a real app, these would be generated by our AI backend
    summary_for_teacher: `[AI Summary for Teacher]: Based on the parent's note about "${title}", please observe the child for related behaviors.`,
    summary_for_doctor: `[AI Summary for Doctor]: Patient's parent reports: "${title}". Description: "${description}".`,
    tags: ['new', 'manual entry'],
  };
  
  console.log("Mock API responded with new log:", newLog);
  return newLog;
};
