
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xbowznjvpqlrdnnaiszc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhib3d6bmp2cHFscmRubmFpc3pjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MjA5MzYsImV4cCI6MjA2NTQ5NjkzNn0.m08gEzFJH2K8HkPf0eyEJrSqjd2rl8OtD6dUZAsO7hE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

console.log('Supabase URL:', SUPABASE_URL);
console.log('Supabase Key (first 20 chars):', SUPABASE_PUBLISHABLE_KEY.substring(0, 20) + '...');

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? window.localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true
  }
});

// Test connection
supabase.auth.getSession().then(({ data, error }) => {
  console.log('Initial session check:', { data: data.session ? 'session exists' : 'no session', error });
}).catch(err => {
  console.error('Error getting initial session:', err);
});
